name: discovery-relay

services:
  app:
    image: "ghcr.io/sondreb/discovery-relay:latest"
    restart: always
    ports:
      - "6565:6565"
    environment:
      Relay__Name: "Discovery Relay"
      Relay__Contact: ""
      Relay__PrivacyPolicy: ""
      Relay__PostingPolicy: ""
      Lmdb__DatabasePath: 'data'
      Lmdb__SizeInMb: 1024
      Lmdb__MaxReaders: 4096
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - /data/:/app/data
