name: Build and Deploy to Azure Web Apps

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:
    inputs:
      azure_webapp_name:
        description: 'Name of the Azure Web App to deploy to'
        required: false
        default: 'nostria-eu-discovery'
        type: string

env:
  AZURE_WEBAPP_NAME: ${{ github.event.inputs.azure_webapp_name || 'nostria-eu-discovery' }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest image digest
        id: get-latest-image
        run: |
          IMAGE_WITH_REGISTRY="${{ env.REGISTRY }}/${{ github.repository_owner }}/discovery-relay"
          DIGEST=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/discovery-relay/versions" \
            | jq -r '[.[] | select(.metadata.container.tags[] | contains("latest"))] | .[0].name')
          FULL_IMAGE_PATH="${IMAGE_WITH_REGISTRY}@${DIGEST}"
          echo "FULL_IMAGE_PATH=${FULL_IMAGE_PATH}" >> $GITHUB_ENV
          echo "Using image: ${FULL_IMAGE_PATH}"

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.FULL_IMAGE_PATH }}

      - name: Azure logout
        run: |
          az logout